
alias_map = {
    "3M COMPANY": "3M COMPANY",
    "3M COMPANY - HEALTH CARE BUSINESS": "3M COMPANY",
    "3M COMPANY, UNITEK ORTHODONTIC PRODUCTS": "3M COMPANY",
    "ABBOTT": "ABBOTT",
    "ABBOTT DIABETES CARE": "ABBOTT",
    "ABBOTT DIAGNOSTICS SCARBOROUGH": "ABBOTT",
    "ABBOTT LABORATORIES": "ABBOTT",
    "ABBOTT MEDICAL": "ABBOTT",
    "ABBOTT MOLECULAR": "ABBOTT",
    "ABBOTT POINT OF CARE": "ABBOTT",
    "ABBOTT VASCULAR": "ABBOTT",
    "ABBOTT VASCULAR (IDEF TECHNOLOGIES )": "ABBOTT",
    # Boston Scientific
    "AGILENT TECHNOLOGIES DENMARK APS": "AGILENT TECHNOLOGIES" ,
    "AUXEIN MEDICAL PRIVATE LIMITED" : "AUXEIN MEDICAL", 
    "AUXEIN MEDICAL PRIVATE LIMITED/71164" : "AUXEIN MEDICAL",  
    # B. BRAUN
    "B.BRAUN MEDICAL": "B. BRAUN",
    
    # BARCO
    "BARCO N.V": "BARCO",
    "BARCO TEKSTIL SANAYI VE TICARET A.S": "BARCO",
    
    # BARD (Racheté par BD, mais souvent traité à part ou sous BARD)
    "BARD ACCESS SYSTEMS": "BARD",
    "BARD PERIPHERAL VASCULAR": "BARD",
    
    # BAUSCH & LOMB
    "BAUSCH & LOMB": "BAUSCH & LOMB",
    "BAUSCH AND LOMB": "BAUSCH & LOMB",
    
    # BAXTER
    "BAXTER BIO SCIENCE": "BAXTER",
    "BAXTER HEALTHCARE": "BAXTER",
    "BAXTER HEALTHCARE CORPORATION": "BAXTER",
    
    # BECTON DICKINSON / BD
    "BD DIAGNOSTIC SYSTEMS": "BD",
    "BD DIAGNOSTICS": "BD",
    "BD SWITZERLAND SARL": "BD",
    "BECTON DICKINSON &": "BD",
    "BECTON DICKINSON & COMPANY": "BD",
    "BECTON DICKINSON INFUSION THERAPY SYSTEMS": "BD",
    "BECTON, DICKINSON AND COMPANY": "BD",
    
    # BECKMAN COULTER
    "BECKMAN COULTER": "BECKMAN COULTER",
    "BECKMAN COULTER IRELAND": "BECKMAN COULTER",
    "BECKMAN COULTER MISHIMA K.K": "BECKMAN COULTER",
    
    # BIOMÉRIEUX
    "BIOMERIEUX": "BIOMERIEUX",
    
    # BIOMET (Appartient désormais à Zimmer Biomet)
    "BIOMET": "BIOMET",
    "BIOMET 3I": "BIOMET",
    "BIOMET MANUFACTURING": "BIOMET",
    "BOSTON SCIENTIFIC CDIDINOSTIC TECHNOLOGIES": "BOSTON SCIENTIFIC",
    "BOSTON SCIENTIFIC RP": "BOSTON SCIENTIFIC",
    "BOSTON SCIENTIFIC RPORION": "BOSTON SCIENTIFIC",
    "BOSTON SCIENTIFIC CORP": "BOSTON SCIENTIFIC",
    "BOTT" : "BOTT",                                             
    "BOTT LORORIES":"BOTT",                                    
    "BOTT MEDIC":"BOTT",
        
    "BRAINLAB": "BRAINLAB",
    
    # BARD
    "C.R. BARD": "BARD",
    
    # CANON MEDICAL
    "CANON MEDICAL SYSTEM, USA": "CANON MEDICAL SYSTEMS",
    "CANON MEDICAL SYSTEMS CORPORATION": "CANON MEDICAL SYSTEMS",
    
    # CARBOFIX (Correction de la faute de frappe "ORTHPEDICS")
    "CARBOFIX ORTHOPEDICS": "CARBOFIX ORTHOPEDICS",
    "CARBOFIX ORTHPEDICS": "CARBOFIX ORTHOPEDICS",
    
    # CARDINAL HEALTH
    "CARDINAL HEALTH": "CARDINAL HEALTH",
    "CARDINAL HEALTH 200": "CARDINAL HEALTH",
    "CARDINAL HEALTH200": "CARDINAL HEALTH",
    
    # CAREFUSION (Filiale de BD, mais souvent isolée dans les rapports)
    "CAREFUSION": "CAREFUSION",
    "CAREFUSION 2200": "CAREFUSION",
    "CAREFUSION 303": "CAREFUSION",
    
    # CARL ZEISS
    "CARL ZEISS MEDITEC": "CARL ZEISS MEDITEC",
    "CEPHEID®": "CEPHEID",
    
    # COCHLEAR
    "COCHLEAR AMERICAS": "COCHLEAR",
    
    # COLOPLAST
    "COLOPLAST A/S": "COLOPLAST",
    "COLOPLAST MANUFACTURING": "COLOPLAST",
    
    # COMPANION SPINE
    "COMPANION SPINE FRANCE": "COMPANION SPINE",
    "COMPANION SPINE FRANCE SAS": "COMPANION SPINE",
    
    # CONMED
    "CONMED CORPORATION": "CONMED",
    
    # COOK MEDICAL
    "COOK INCORPORATED": "COOK MEDICAL",
    "COOK IRELAND": "COOK MEDICAL",
    "COOK MEDICAL INCORPORATED": "COOK MEDICAL",
    "COOK": "COOK MEDICAL",
    
    # CORCYM
    "CORCYM CANADA": "CORCYM",
    "CORCYM S.R.L": "CORCYM",
    "DATASCOPE CORPORATION": "DATASCOPE",
    "DATEX--OHMEDA": "DATEX-OHMEDA",
    
    # DAVOL (Filiale de Bard / BD, regroupée sous BARD comme demandé avant)
    "DAVOL": "BARD",
    "DAVOL ., SUBSIDIARY OF C. R. BARD": "BARD",
    
    # DEPUY (Filiale orthopédique de Johnson & Johnson)
    "DEPUY": "DEPUY",
    "DEPUY IRELAND UC": "DEPUY",
    "DEPUY ORTHOPAEDICS": "DEPUY",
    
    # DIXI MEDICAL
    "DIXI MEDICAL USA": "DIXI MEDICAL",
    
    # DJO
    "DJO GLOBAL": "DJO",
    
    # DRAEGER
    "DRAEGER MEDICAL": "DRAEGER",
    "DRAEGER MEDICAL SYSTEMS": "DRAEGER",
    # Medtronic
    "MEDTRONIC SOFAMOR DANEK": "MEDTRONIC",
    "MEDTRONIC VASCULAR": "MEDTRONIC",
    # EDAN
    "EDAN DIAGNOSTICS": "EDAN INSTRUMENTS",
    "EDAN INSTRUMENTS": "EDAN INSTRUMENTS",
    
    # EDWARDS LIFESCIENCES (Correction de la faute de frappe "LIFESIENCES")
    "EDWARDS LIFESCIENCES": "EDWARDS LIFESCIENCES",
    "EDWARDS LIFESIENCES": "EDWARDS LIFESCIENCES",
    
    # ELEKTA
    "ELEKTA INSTRUMENT AB": "ELEKTA",
    
    # ETHICON (Filiale chirurgicale de Johnson & Johnson)
    "ETHICON ENDO-SURGERY": "ETHICON",
    
    # ev3 (Medtronic)
    "EV3 NEUROVASCULAR": "EV3",
    
    # EXACTECH
    "EXACT MEDICAL MANUFACTURING": "EXACTECH",
    "FRESENIUS KABI USA": "FRESENIUS",
    "FRESENIUS MEDICAL CARE HOLDINGS": "FRESENIUS",
    
    # FUJIFILM
    "FUJIFILM CORPORATION": "FUJIFILM",
    "FUJIFILM CORPORATON": "FUJIFILM",  # Correction faute de frappe
    "FUJIFILM HEALTHCARE AMERICAS CORPORATION": "FUJIFILM",
    "FUJIFILM HEALTHCARE CORPORATION": "FUJIFILM",
    
    # FUJIREBIO
    "FUJIREBIO DIAGNOSTICS": "FUJIREBIO",
    "FUJIREBIO EUROPE N.V": "FUJIREBIO",
    
    # GE HEALTHCARE / GE MEDICAL SYSTEMS
    "GE HEALTHCARE": "GE HEALTHCARE",
    "GE HEALTHCARE (CHINA)": "GE HEALTHCARE",
    "GE HEALTHCARE (TIANJIN) COMPANY LIMITED": "GE HEALTHCARE",
    "GE MEDICAL SYSTEMS": "GE HEALTHCARE",
    "GE MEDICAL SYSTEMS CHINA": "GE HEALTHCARE",
    "GE MEDICAL SYSTEMS INFORMATION TECHNOLOGIES": "GE HEALTHCARE",
    "GE MEDICAL SYSTEMS ISRAEL, FUNCTIONAL IMAGING": "GE HEALTHCARE",
    "GE MEDICAL SYSTEMS SCS": "GE HEALTHCARE",
    "GE MEDICAL SYSTEMS ULTRASOUND AND PRIMARY CARE DIAGNOSTICS": "GE HEALTHCARE",
    "GE MEDICAL SYSTEMS, ISRAEL": "GE HEALTHCARE",
    
    # GEISTLICH PHARMA
    "GEISTLICH PHARMA": "GEISTLICH PHARMA",
    "GEISTLICH PHARMA NORTH AMERICA": "GEISTLICH PHARMA",
    
    # GETINGE
    "GETINGE GROUP LOGISTICS AMERICA": "GETINGE",
    "GETINGE USA SALES": "GETINGE",
    "GUILIN HBM HEALTH PROTECTIONS": "GUILIN HBM",
    "GUILIN HBM SANITARY PROTECTIONS": "GUILIN HBM",
    
    # HEARTWARE (Medtronic)
    "HEARTWARE": "HEARTWARE"
    "PHILIPS HETH CE": "PHILIPS",
    "PHILIPS HETHCE (SUZHOU)": "PHILIPS",
    "PHILIPS MEDICSYSTEMS NEDERLD": "PHILIPS",
    "PHILIPS MEDICSYSTEMS NEDERLDS": "PHILIPS",
    "PHILIPS ULTROUND": "PHILIPS"
}
